version: 1

sources:
  # files or directories to be excluded
  exclusions:
    - "build"
    - "dist"
    - "node_modules"
    - ".git"

# Specify the languages you would like to scan. default is all
languages: "JAVASCRIPT,TYPESCRIPT,HTML,CSS"
